config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: 'questions#index'

  post 'users/auth_without_email', to: 'users#auth_without_email', as: :auth_without_email

  concern :votable do
    member do
      post :like
      post :dislike
      post :cancel_vote
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create destroy update] do
      member do
        post :mark_as_best
        delete 'purge/:file', to: 'answers#purge', as: 'purge'
      end
    end

    delete 'purge/:file', to: 'questions#purge', as: 'purge', on: :member

    resource :subscription, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :rewards, only: :index

  get 'results', to: 'results#index', as: 'results'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include HasSearch
  include HasLink
  include HasAttachedFiles
  include HasVote
  include HasComment

  multisearchable against: [:title, :body]
  pg_search_scope :search, against: [:title, :body]

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscribe!

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe!
    user.subscriptions.create(question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      include Rails.application.routes.url_helpers

      authorize_resource

      def index
        @questions = Question.all
        render json: @questions, each_serializer: QuestionsSerializer
      end

      def show
        render json: question
      end

      def create
        @question = current_resource_owner.questions.new(question_params)

        if @question.save
          render json: @question
        else
          render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def update
        if question.update(question_params)
          render json: question
        else
          render json: { errors: question.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        question.destroy
      end

      private

      def question
        @question ||= Question.find(params[:id]) if params[:id]
      end

      def question_params
        params.require(:question).permit(:title, :body,
                                         links_attributes: %i[id name url _destroy],
                                         reward_attributes: %i[title image])
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :gon_question_id, only: [:show]
  before_action :gon_question_user_id, only: [:show]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def new
    question.links.new
    reward = Reward.new
    question.reward = reward
  end

  def show
    @answer = question.answers.new
    @answer.links.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def edit; end

  def destroy
    if can?(:destroy, question)
      question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted!'
    else
      redirect_to question_path(question), notice: 'Only the author can delete a question!'
    end
  end

  def purge
    file = question.files.find(params[:file])
    file.purge
    redirect_to question_path(question)
  end

  private

  def gon_question_id
    gon.question_id = question.id
  end

  def gon_question_user_id
    gon.question_user_id = question.user_id
  end

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast('questions', question)
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: %i[id name url _destroy],
                                                    reward_attributes: %i[title image])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache question do
  h1= question.title
  p= question.body

  .subscription
    - if can?(:create, Subscription)
      - if current_user.subscribed?(question)
        = button_to 'Unsubscribe', question_subscription_path(question), method: :delete, remote: true, class: 'btn btn-primary'
      - else
        = button_to 'Subscribe', question_subscription_path(question), method: :post, remote: true, class: 'btn btn-primary'

  -if question.files.attached?
    -question.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      -if can?(:purge, question)
        = link_to 'Delete file', purge_question_path(question, file), method: :delete
        br

  .links
    -if question.links.present?
      p Links:
      ul
        -question.links.each do |link|
          li= link_to link.name, link.url
          -if link.gist?
            code data-gist-id=link.gist_id

  .vote
    'Rating:
    .rating
      = question.rating
      br

    - if can?(:like, question)
      'Vote the question
      br
      div class="vote-buttons #{display_buttons(question)}"
        = link_to '+', like_question_path(question), method: :post, remote: true
        br
        = link_to '-', dislike_question_path(question), method: :post, remote: true

      = link_to 'Cancel vote', cancel_vote_question_path(question),
                               method: :post, remote: true,
                               class: "cancel-vote #{hide_buttons(question)}"

  - if can?(:update, question)
    = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    br
    .question-errors
      = render 'shared/errors', resource: question

    = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title, 'Your question'
      br
      = f.text_field :title
      br
      = f.label :body
      br
      = f.text_area :body
      br
      = f.label :files
      br
      = f.file_field :files, multiple: true, direct_upload: true
      br
      p Links:
      div id='question-links'
        = f.fields_for :links do |l|
          = render 'link_fields', f: l
        .links
          = link_to_add_association 'Add link', f, :links
      = f.submit 'Save'

  - if can?(:destroy, question)
    = link_to 'Delete question', question, method: :delete

  .comments
    - if question.comments.present?
      b Comments:
      = render question.comments.order(:created_at)

  .comments-form
    -if can?(:add_comment, question)
      = render 'comments/form', commentable: question

app/views/questions/_reward_fields.html.slim
.nested-fields
  .field
    = f.label :title, 'Reward name'
    br
    = f.text_field :title
  .field
    = f.label :image
    br
    = f.file_field :image, accept: 'image/*'

app/views/questions/add_comment.js.erb
<% if @comment.persisted? %>
  $('.question .comments').append('<%= j render @comment %>');
  $('.question .comments-form #body').val('');
<% end %>

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

- cache collection_cache_key_for :question do
  h2 Questions

  .questions-list
    -@questions.each do |n|
      = link_to "#{n.title}", question_path(n)
      br

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  p
    = f.label :title
    br
    = f.text_field :title
  p
    = f.label :body
    br
    = f.text_area :body
  p
    = f.label :files
    br
    = f.file_field :files, multiple: true

  p Reward:
  div id='reward'
    = f.fields_for :reward do |r|
      = render 'reward_fields', f: r

  p Links:
  div id='links'
    = f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'Add link', f, :links
  p= f.submit 'Ask'

app/views/questions/show.html.slim
.div id='question-id' data-question-id="#{question.id}"
.question
  = render question

h2 Answers

.answers
  = render question.answers.sort_by_best

.answer-errors
  = render 'shared/errors', resource: @answer

= form_with model: [question, @answer], local: false, class: 'new-answer' do |f|
  = f.label :body, 'Your Answer'
  br
  = f.text_area :body
  br
  = f.label :files
  br
  = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  div id='links'
    = f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'Add link', f, :links
  p= f.submit 'Post Your Answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');

<% unless question.errors.present? %>
  $('.question').html('<%= j render question %>');
  window.GistEmbed.init();
<% end %>