config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: 'questions#index'

  post 'users/auth_without_email', to: 'users#auth_without_email', as: :auth_without_email

  concern :votable do
    member do
      post :like
      post :dislike
      post :cancel_vote
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create destroy update] do
      member do
        post :mark_as_best
        delete 'purge/:file', to: 'answers#purge', as: 'purge'
      end
    end

    delete 'purge/:file', to: 'questions#purge', as: 'purge', on: :member

    resource :subscription, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :rewards, only: :index

  get 'results', to: 'results#index', as: 'results'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities

    can :me, User
    can :destroy, [Subscription]
    can :create, [Question, Answer, Subscription]
    can :add_comment, [Question, Answer]
    can %i[update destroy purge], [Question, Answer], user_id: user.id
    can :mark_as_best, Answer, question: { user_id: user.id }
    can %i[like dislike cancel_vote], [Question, Answer] do |votable|
      votable.user_id != user.id
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include HasSearch
  include HasLink
  include HasAttachedFiles
  include HasVote
  include HasComment

  multisearchable against: :body
  pg_search_scope :search, against: :body

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, presence: true

  after_create :send_notice

  scope :sort_by_best, -> { order(best: :desc) }

  def mark_as_best
    transaction do
      self.class.where(question_id: question_id).update_all(best: false)
      update(best: true)
    end
  end

  private

  def send_notice
    NewAnswerJob.perform_later(self)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include HasSearch

  multisearchable against: :body
  pg_search_scope :search, against: :body

  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, presence: true

end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, url: true

  def gist?
    url.include?('https://gist.github.com/')
  end

  def gist_id
    url.split('/').last
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include HasSearch
  include HasLink
  include HasAttachedFiles
  include HasVote
  include HasComment

  multisearchable against: [:title, :body]
  pg_search_scope :search, against: [:title, :body]

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscribe!

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe!
    user.subscriptions.create(question: self)
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  has_one_attached :image

  validates :title, presence: true
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include HasSearch
  include HasComment

  multisearchable against: [:email, :id]
  pg_search_scope :search, against: [:email, :id]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :confirmable,
         omniauth_providers: %i[github vkontakte]

  def self.find_for_oauth(auth)
    FindForOauthService.new(auth).call
  end

  def create_authorization(auth)
    authorizations.create!(provider: auth.provider, uid: auth.uid)
  end

  def voted?(resource)
    votes.where(votable_id: resource).present?
  end

  def author?(resource)
    resource.user_id == id
  end

  def subscribed?(question)
    subscriptions.find_by(question: question)
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def auth_without_email
    return redirect_to root_path unless session[:oauth]

    password = Devise.friendly_token[0, 20]
    @user = User.new(email: user_params[:email], password: password, password_confirmation: password)

    if @user.save
      @user.create_authorization(oauth)
      redirect_to root_path
    else
      render :auth_without_email
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

  def oauth
    Struct.new(:provider, :uid).new(session[:oauth]['provider'], session[:oauth]['uid'])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def display_buttons(resource)
    'hidden' if current_user.voted?(resource)
  end

  def hide_buttons(resource)
    'hidden' unless current_user.voted?(resource)
  end

  def flash_message(argument)
    return unless flash[argument].present?

    content_tag :div, flash[argument], class: "flash #{argument}"
  end

  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/confirmations_helper.rb
# frozen_string_literal: true

module ConfirmationsHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/rewards_helper.rb
# frozen_string_literal: true

module RewardsHelper
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= include_gon(:init => true) %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.slim
.row.justify-content-center
  - if flash_message(:alert).present?
    .alert.alert-warning.text-center.gy-2 role="alert"
      = flash_message(:alert)
  - elsif flash_message(:notice).present?
    .alert.alert-primary.text-center.gy-2 role="notice"
      = flash_message(:notice)

app/views/shared/_nav.html.slim
.nav.navbar-expand-lg.navbar-dark.bg-dark
  .container.container-fluid.p-1
    .collapse.navbar-collapse id='navbarSupportedContent'
      = link_to 'QNA', root_path, class: 'navbar-brand nav-link'
      .navbar-nav
        - if user_signed_in?
          = link_to 'Rewards', rewards_path, class: 'nav-link navbar-item me-3'
          = render 'shared/search_form'
          = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          = render 'shared/search_form'
          = link_to 'Sign in', new_user_session_path, class: 'nav-link me-3'
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link me-3'

app/views/shared/_search_form.html.slim
= form_tag results_path, method: :get, role: 'search', class: 'form-inline' do
  = text_field_tag :query, params[:query],  type: 'search', class: 'rounded me-2', placeholder: 'Search'
  = select_tag :resource, options_for_select(%w[All Question User Comment Answer], 'All'), class: 'me-2'
  = submit_tag "Search", name: nil, class: 'btn btn-outline-primary me-3'