config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: 'questions#index'

  post 'users/auth_without_email', to: 'users#auth_without_email', as: :auth_without_email

  concern :votable do
    member do
      post :like
      post :dislike
      post :cancel_vote
    end
  end

  concern :commentable do
    member { post :add_comment }
  end

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create destroy update] do
      member do
        post :mark_as_best
        delete 'purge/:file', to: 'answers#purge', as: 'purge'
      end
    end

    delete 'purge/:file', to: 'questions#purge', as: 'purge', on: :member

    resource :subscription, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :rewards, only: :index

  get 'results', to: 'results#index', as: 'results'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include HasSearch
  include HasLink
  include HasAttachedFiles
  include HasVote
  include HasComment

  multisearchable against: :body
  pg_search_scope :search, against: :body

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, presence: true

  after_create :send_notice

  scope :sort_by_best, -> { order(best: :desc) }

  def mark_as_best
    transaction do
      self.class.where(question_id: question_id).update_all(best: false)
      update(best: true)
    end
  end

  private

  def send_notice
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @question = answer.question
    answer.destroy
  end

  def update
    answer.update(answer_params)
    @question = answer.question
  end

  def mark_as_best
    answer.mark_as_best
    @question = answer.question
    set_reward if @question.reward
  end

  def purge
    @question = answer.question
    file = answer.files.find(params[:file])
    file.purge
  end

  private

  def publish_answer
    return if answer.errors.any?

    ActionCable.server.broadcast("answers_channel_#{answer.question.id}", answer)
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  def set_reward
    reward = @question.reward
    reward.user = answer.user
    reward.save
  end

  helper_method :answer
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      authorize_resource

      def index
        @answers = question.answers
        render json: @answers, each_serializer: AnswersSerializer
      end

      def show
        render json: answer
      end

      def create
        @answer = question.answers.new(answer_params)
        @answer.user = current_resource_owner

        if @answer.save
          render json: @answer
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def update
        if answer.update(answer_params)
          render json: answer
        else
          render json: { errors: answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        answer.destroy
      end

      private

      def question
        @question ||= Question.find(params[:question_id])
      end

      def answer
        @answer ||= Answer.find(params[:id])
      end

      def answer_params
        params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div[id="answer-#{answer.id}"]
    - if answer.best
      'Best answer:
      br
    p= answer.body

    .links
      - if answer.links.present?
        p Links:
        ul
          - answer.links.each do |link|
            li
              = link_to link.name, link.url
              - if link.gist?
                code data-gist-id=link.gist_id

    - if answer.files.attached?
      - answer.files.each do |file|
        br
        = link_to file.filename.to_s, url_for(file)
        - if can?(:purge, answer)
          br
          = link_to 'Delete file', purge_answer_path(answer, file), method: :delete, remote: true
          br

    .vote
      'Rating:
      .rating
        = answer.rating
        br

      -if can?(:like, answer)
        'Vote the answer
        br
        div class="vote-buttons #{display_buttons(answer)}"
          = link_to '+', like_answer_path(answer), method: :post, remote: true
          br
          = link_to '-', dislike_answer_path(answer), method: :post, remote: true

        = link_to 'Cancel vote', cancel_vote_answer_path(answer), method: :post,
                                remote: true, class: "cancel-vote #{hide_buttons(answer)}"

    .mark-as-best
      - if can?(:mark_as_best, answer) && answer.persisted? && !answer.best
        = link_to 'Best', mark_as_best_answer_path(answer), method: :post, remote: true

    - if answer.persisted? && can?(:destroy, answer)
      = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true

    - if answer.persisted? && can?(:update, answer)
      br
      = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

      = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, 'Your answer'
        br
        = f.text_area :body
        br
        = f.label :files
        br
        = f.file_field :files, multiple: true, direct_upload: true
        p Links:
        div id='links'
          = f.fields_for :links do |l|
            = render 'link_fields', f: l
          .links
            = link_to_add_association 'Add link', f, :links
        p= f.submit 'Save'


    .comments
      - if answer.comments.present?
        b Comments:
        = render answer.comments.order(:created_at)

    .comments-form
      - if can?(:add_comment, answer)
        = render 'comments/form', commentable: answer

  br

app/views/answers/add_comment.js.erb
<% if @comment.persisted? %>
  $('#<%= "answer-#{@commentable.id}" %> .comments').append('<%= j render @comment %>');
  $('.comments-form #body').val('');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer #answer_body').val('');
  $('.new-answer #answer_links_attributes_0_name').val('');
  $('.new-answer #answer_links_attributes_0_url').val('');
  window.GistEmbed.init();
<% end %>

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render @question.answers %>');
window.GistEmbed.init();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render @question.answers.sort_by_best %>');
window.GistEmbed.init();

app/views/answers/purge.js.erb
$('.answers').html('<%= j render @question.answers %>');
window.GistEmbed.init();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
  window.GistEmbed.init();
<% end %>